import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from './components/Header'
import { BacktoTopButton } from './components/BacktoTopButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Estacionamento',
  description: 'Generated by create next app',
  icons: [
    {
      url: '/images/avanade-logo.png',
    },
  ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark:bg-gray-800 flex flex-col gap-1`}
      >
        <Header />
        {children}
        <BacktoTopButton />
      </body>
    </html>
  )
}
